=== Fizahere/XML/fiza_xml/external.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT company (employe* , client)>
<!ELEMENT employe (name,email,password,number)>
<!ELEMENT client (name,email,password)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT number (#PCDATA)>

<!ATTLIST email domain CDATA #FIXED "google">

=== Fizahere/XML/fiza_xml/externaldtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "external.dtd" [
<!ENTITY ps "pass1122">
]>

<company>

    <employe>
        <name>ali</name>
 <email>ali@gmail.com</email>
 <password>9897</password>
 <number>03512154878</number>
    </employe>

    <employe>
        <name>hamza</name>
 <email domain="google">hamza@gmail.com</email>
 <password>45445</password>
 <number>0212154878</number>
    </employe>

    <employe>
        <name>rafay</name>
        <email domain="google">rafay@gmail.com</email>
 <password>2233</password>
 <number>031548787</number>
    </employe>

    <client>
        <name>ali</name>
        <email domain="google">ali@gmail.com</email>
 <password>1234 &ps;</password>
    </client>

</company>
